### ISSUE TITLE
IntegrityError: (1062, "Duplicate entry 'facebook-1660598734' for key 'provider'")

### ISSUE THREAD

**Issue by sidmitra** [omab/django-social-auth#131]
I run social_auth in production, and i keep seeing errors like the following, for twitter/facebook/linkedin. i.e. the 3 backends i use.

``` python
Traceback (most recent call last):

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 39, in wrapped_view
    resp = view_func(*args, **kwargs)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 52, in wrapped_view
    return view_func(*args, **kwargs)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/transaction.py", line 217, in inner
    res = func(*args, **kwargs)

  File "/home/ubuntu/.virtualenvs/app/src/social-auth/social_auth/views.py", line 58, in wrapper
    return func(request, backend, *args, **kwargs)

  File "/home/ubuntu/.virtualenvs/app/src/social-auth/social_auth/views.py", line 75, in complete
    return complete_process(request, backend)

  File "/home/ubuntu/.virtualenvs/app/src/social-auth/social_auth/views.py", line 130, in complete_process
    user = auth_complete(request, backend)

  File "/home/ubuntu/.virtualenvs/app/src/social-auth/social_auth/views.py", line 165, in auth_complete
    user = backend.auth_complete(user=user)

  File "/home/ubuntu/.virtualenvs/app/src/social-auth/social_auth/backends/facebook.py", line 83, in auth_complete
    return authenticate(*args, **kwargs)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/contrib/auth/__init__.py", line 55, in authenticate
    user = backend.authenticate(**credentials)

  File "/home/ubuntu/.virtualenvs/app/src/social-auth/social_auth/backends/__init__.py", line 132, in authenticate
    social_user = self.associate_auth(user, uid, response, details)

  File "/home/ubuntu/.virtualenvs/app/src/social-auth/social_auth/backends/__init__.py", line 210, in associate_auth
    provider=self.name)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/manager.py", line 138, in create
    return self.get_query_set().create(**kwargs)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/query.py", line 360, in create
    obj.save(force_insert=True, using=self.db)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/base.py", line 553, in save_base
    result = manager._insert(values, return_id=update_pk, using=using)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/manager.py", line 195, in _insert
    return insert_query(self.model, values, **kwargs)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/query.py", line 1436, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 791, in execute_sql
    cursor = super(SQLInsertCompiler, self).execute_sql(None)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 86, in execute
    return self.cursor.execute(query, args)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)

  File "/home/ubuntu/.virtualenvs/app/lib/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue

IntegrityError: (1062, "Duplicate entry 'facebook-1660598734' for key 'provider'")
```

**Comment by Python4569** [comment]
This error continues...
