### ISSUE TITLE
Social auth is propagating HTTPError

### ISSUE THREAD

**Issue by antonagestam** [omab/django-social-auth#740]
Social auth is propagating the HTTPError below. I'd expect this to be caught. Will look into it further and possibly submit a patch. Please comment if you want more information.

```
Traceback (most recent call last):

File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
  response = callback(request, *callback_args, **callback_kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/object_wrapper.py", line 220, in __call__
  self._nr_instance, args, kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/hooks/framework_django.py", line 475, in wrapper
  return wrapped(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/decorators.py", line 29, in wrapper
  return func(request, request.social_auth_backend, *args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/views.py", line 30, in auth
  return auth_process(request, backend)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/views.py", line 96, in auth_process
  return HttpResponseRedirect(backend.auth_url())
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 622, in auth_url
  token = self.unauthorized_token()
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 681, in unauthorized_token
  return Token.from_string(self.fetch_response(request))
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 703, in fetch_response
  response = dsa_urlopen(request.to_url())
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/utils.py", line 233, in dsa_urlopen
  return urlopen(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 127, in urlopen
  return _opener.open(url, data, timeout)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/object_wrapper.py", line 220, in __call__
  self._nr_instance, args, kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/api/external_trace.py", line 60, in dynamic_wrapper
  return wrapped(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 410, in open
  response = meth(req, response)
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 523, in http_response
  'http', request, response, code, msg, hdrs)
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 448, in error
  return self._call_chain(*args)
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 382, in _call_chain
  result = func(*args)
File "/app/.heroku/python/lib/python2.7/urllib2.py", line 531, in http_error_default
  raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by paulocheque** [comment]
Hypothesis
- It appears to be a Heroku network issue (Heroku proxy or something).
- Check the Python in the runtime.txt file
- Maybe the User-Agent: Python-urllib/2.7 is forbidden by the service.
- Service throttle blocks Heroku's IPs because there are too many requests

**Comment by antonagestam** [comment]
@paulocheque What makes you think it's a Heroku network issue? The user agent was definitely not forbidden as this was a rare error. Might have been a throttle, but in that case, shouldn't social auth handle it gracefully?

**Comment by paulocheque** [comment]
They are just hypothesis, sorry, I have edited my message inform that.

I have faced similar problems with different tools. Using python requests instead of urllib help me to understand the problem. In my case, it was a throttle problem of the Google API.
