### ISSUE TITLE
Value too long DatabaseError with LinkedIn backend

### ISSUE THREAD

**Issue by antonagestam** [omab/django-social-auth#784]
DatabaseError: value too long for type character varying(30)

```
Traceback (most recent call last):
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/hooks/framework_django.py", line 475, in wrapper return wrapped(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view return view_func(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/decorators.py", line 29, in wrapper return func(request, request.social_auth_backend, *args,\ **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/views.py", line 41, in complete return complete_process(request, backend, *args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/views.py", line 107, in complete_process user = auth_complete(request, backend, *args,\ **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/views.py", line 190, in auth_complete return backend.auth_complete(user=user, request=request,\ *args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/contrib/linkedin.py", line 127, in auth_complete return super(LinkedinAuth, self).auth_complete(*args,\ **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 681, in auth_complete return self.do_auth(access_token, *args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 697, in do_auth return authenticate(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 45, in authenticate user = backend.authenticate(**credentials)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 114, in authenticate out = self.pipeline(pipeline, *args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/__init__.py", line 143, in pipeline result = func(*args, **out) or {}
File "/app/.heroku/python/lib/python2.7/site-packages/social_auth/backends/pipeline/user.py", line 134, in update_user_details user.save()
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save self.save_base(using=using, force_insert=force_insert,\ force_update=force_update)
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 529, in save_base rows = manager.using(using).filter(pk=pk_val)._update(values)
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 560, in _update return query.get_compiler(self.db).execute_sql(None)
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 988, in execute_sql cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql cursor.execute(sql, params)
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute return self.cursor.execute(query, args)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.10.2.38/newrelic/hooks/database_dbapi2.py", line 36, in execute return self._nr_cursor.execute(sql, *args, **kwargs)
DatabaseError: value too long for type character varying(30)
```

**Comment by jpatel3** [comment]
@omab is above modification in pipeline is still the best possible solution? I am running into similar issue with username field coming from google social signin, and would like to add truncation so that user creation doesn't fail.
