### ISSUE TITLE
can't run  example app

### ISSUE THREAD

**Issue by yishenggudou** [omab/django-social-auth#811]
got a  error message

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/management/commands/runserver.py", line 93, in inner_run
    self.validate(display_num_errors=True)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 280, in validate
    num_errors = get_validation_errors(s, app)
  File "/Library/Python/2.7/site-packages/django/core/management/validation.py", line 35, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Library/Python/2.7/site-packages/django/db/models/loading.py", line 166, in get_app_errors
    self._populate()
  File "/Library/Python/2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name)
  File "/Library/Python/2.7/site-packages/django/db/models/loading.py", line 96, in load_app
    models = import_module('.models', app_name)
  File "/Library/Python/2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "../social_auth/models.py", line 8, in <module>
    from social.apps.django_app.default.models import \
ImportError: No module named social.apps.django_app.default.models
^Ctimger-mac:example timger$ python manage.py  syncdb
ImportError: No module named social.apps.django_app.default.models
```

**Comment by andresgarciadev** [comment]
u need to install requeriments.txt
see that
http://www.williamjohnbert.com/2011/08/django-social-auth-installing-and-troubleshooting/
too need  install oauth
and update oauthlib
