### ISSUE TITLE
Django 1.8 does not supported?

### ISSUE THREAD

**Issue by shinriyo** [omab/django-social-auth#824]
I tried to install but error occured.

```
Downloading/unpacking oauth2>=1.5.167 (from django-social-auth)
  Downloading oauth2-1.5.211.tar.gz
  Running setup.py (path:/Users/shinriyo/.virtualenvs/tokyo-django-meetup/build/oauth2/setup.py) egg_info for package oauth2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/shinriyo/.virtualenvs/tokyo-django-meetup/build/oauth2/setup.py", line 18
        print "unable to find version in %s" % (VERSIONFILE,)
                                           ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/shinriyo/.virtualenvs/tokyo-django-meetup/build/oauth2/setup.py", line 18

    print "unable to find version in %s" % (VERSIONFILE,)

                                       ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/shinriyo/.virtualenvs/tokyo-django-meetup/build/oauth2
Storing debug log for failure in /Users/shinriyo/.pip/pip.log
```

Does it support for Django 1.8?

**Comment by sreejithr** [comment]
@shinriyo What version were you trying to install? Looks like an error with oauth2. Tell me the version so I can try to reproduce.
