### ISSUE TITLE
Problem with django 1.8.1

### ISSUE THREAD

**Issue by FTCr** [omab/django-social-auth#825]
After adding the application in settings.py and run ./manage.py syncdb

``` python
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 207, in handle
    changes = autodetector.changes(graph=executor.loader.graph)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 110, in _detect_changes
    self.old_apps = self.from_state.concrete_apps
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/db/migrations/state.py", line 170, in concrete_apps
    self.apps = StateApps(self.real_apps, self.models, ignore_swappable=True)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/Volumes/WDC/Documents/Development/Web/steam-trading.com/lib/python3.4/site-packages/django/db/migrations/state.py", line 270, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'social_auth.UserSocialAuth'>, <ModelState: 'social_auth.Nonce'>, <ModelState: 'social_auth.Association'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more
```

**Comment by geneinmylife** [comment]
I met the same problem using django 1.8.3 Can I ask how to solve it?

**Comment by Jzarecta** [comment]
I am using 1.8.2 wonder if you got to fix this and how?

**Comment by TakesxiSximada** [comment]
I'm in the same boat. 
using 
- Django==1.8.7
- python-social-auth==0.2.13
- django-social-auth: 699571a3b6d84aa2c25ffce59daa4c7f3559a0e4
- Python 3.5.0
