### ISSUE TITLE
No module named 'django.utils.importlib' in Django 1.10.1

### ISSUE THREAD

**Issue by n2k3bu1** [omab/django-social-auth#841]
I have a issue with Django 1.10.1 when migrate command line. Could you help me to fix it.

(framework_env35) nake@ubuntux:/webapps/fantasy$ **python manage.py migrate**
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/framework_env35/lib/python3.5/site-packages/django/core/management/**init**.py", line 367, in execute_from_command_line
    utility.execute()
  File "/webapps/framework_env35/lib/python3.5/site-packages/django/core/management/**init**.py", line 341, in execute
    django.setup()
  File "/webapps/framework_env35/lib/python3.5/site-packages/django/**init**.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/webapps/framework_env35/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/webapps/framework_env35/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/webapps/framework_env35/lib/python3.5/importlib/**init**.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  **File "/webapps/framework_env35/lib/python3.5/site-packages/social_auth/models.py", line 4, in <module>**
    from django.utils.importlib import import_module
**ImportError: No module named 'django.utils.importlib'**

**Comment by shlaikov** [comment]
I have the same problem when _migrate_ and _runserver_.
Are you fix this problem?

_Django==1.9.2
django-social-auth==0.7.28_

**Comment by cdman** [comment]
Apparently importlib has been deprecated since Django 1.7 and removed in Django 1.9: https://docs.djangoproject.com/en/1.10/releases/1.7/#django-utils-dictconfig-django-utils-importlib

**Comment by n2k3bu1** [comment]
Thank cdman for related issue. However, It seems that social_auth is not maintained well.
I will work around another way.

**Comment by cdman** [comment]
@bsninh78 - yes, that's also the impression I have :frowning: In the end I ended up using [banana_py](https://github.com/brack3t/Banana-Py) - (I only need mailchimp login for now)
