### ISSUE TITLE
ImportError: No module named importlib

### ISSUE THREAD

**Issue by s0nskar** [omab/django-social-auth#846]
Getting this on running `python manage.py runserver`

```
Unhandled exception in thread started by <function wrapper at 0x7f1576b4e410>
Traceback (most recent call last):
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/maniac/.virtualenvs/DIH/local/lib/python2.7/site-packages/social_auth/models.py", line 4, in <module>
    from django.utils.importlib import import_module
ImportError: No module named importlib
```

**Comment by dorantor** [comment]
Not 100% sure, but it seems problem is with old package in pypi. Last version there is 0.7.28, while current latest is 0.8.1.
